//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPage_Ex.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class ProductTable
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Price { get; set; }
        public string Brand { get; set; }
        public string Type { get; set; }
        public string Details { get; set; }
        public byte[] ImageData { get; set; }
        public HttpPostedFileBase File { get; set; }
    }
}
